title: "Ca.io"
description: Personal blog to share my learning about programming languages
author: Caio Lima
github: https://github.com/caiolima
about: "I'm a programmer that is very interested in programming languages and operating systems"

enableTags: true
tagarray: []

social:
    - icon: fa-twitter
      link: "https://twitter.com/caio_nepo"
    - icon: fa-linkedin
      link: "linkedin.com/in/caionepo"
    - icon: fa-github
      link: "https://github.com/caiolima"

url: "https://caiolima.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
